INSERT INTO ITEMESTOQUE (NOME, UNIDADEMEDIDA, PRECOMEDIO) VALUES ('Farinha integral', 'KG', 0.00);
INSERT INTO ITEMESTOQUE (NOME, UNIDADEMEDIDA, PRECOMEDIO) VALUES ('Linhaça marrom', 'KG', 0.00);
INSERT INTO ITEMESTOQUE (NOME, UNIDADEMEDIDA, PRECOMEDIO) VALUES ('Semente girassol', 'KG', 0.00);
INSERT INTO ITEMESTOQUE (NOME, UNIDADEMEDIDA, PRECOMEDIO) VALUES ('Aveia em flocos', 'KG', 0.00);